apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhellworldhelmdeployment
  namespace: default
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      tier: python
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        tier: python
    spec: # Pod spec
      containers:
      - name: hello
        image: raviroc/hello:latest
        ports:
        - containerPort: 80
