name: Build and check a Docker image core

on: push

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      TAG: python-check
      USER: raviroch
      REGISTRY: ghcr.io
      VERSION: v1
